routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/init', 'PageController@init')->name('init'); // TODO : Delete après
Route::get('/', 'PageController@index')->name('home');
Route::get('/lang/{id}', 'PageController@lang')->name('lang.choose');
Route::get('/about', 'PageController@about')->name('about');
Route::get('/faq', 'PageController@faq')->name('faq');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::post('/contact', 'PageController@postContact')->name('contact.post');
Route::get('/terms', 'PageController@terms')->name('terms');
Route::get('/privacy', 'PageController@privacy')->name('privacy');
Route::get('/copyright', 'PageController@copyright')->name('copyright');
Route::get('/report', 'PageController@report')->name('report');
Route::get('/register', 'AuthController@register')->name('register');
Route::post('/register', 'AuthController@postRegister')->name('register.post');
Route::get('/logout', 'AuthController@logout')->name('logout');
Route::post('/login', 'AuthController@postLogin')->name('login');
Route::post('/login', 'AuthController@postLogin')->name('login');
Route::get('/forgotpassword', 'AuthController@forgotPassword')->name('forgot_password');
Route::post('/forgotpassword', 'AuthController@postForgotPassword')->name('forgot_password.post');
Route::get('/resetpassword/{email}/{token}', 'AuthController@resetPassword')->name('reset_password');
Route::post('/resetpassword/{email}/{token}', 'AuthController@postResetPassword')->name('reset_password.post');
Route::post('/upload', 'UploadController@ajax')->name('upload.ajax');
Route::get('/d/{slug}/{token}', 'UploadController@delete')->name('upload.delete');
Route::get('/f/{slug}', 'PageController@file')->name('file');
Route::get('/d/{slug}', 'DownloadController@download')->name('download');
Route::get('/json/downloads/stats/{period}', 'DownloadController@stats')->name('download.stats');
Route::get('/json/money/stats', 'Dashboard\FinanceController@stats')->name('money.stats');
Route::get('/v/{slug}', 'PageController@video')->name('video');

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'noguest'], function(){
    Route::get('/', 'Dashboard\HomeController@index')->name('index');
    Route::get('/files', 'Dashboard\FileController@index')->name('files');
    Route::get('/files/{slug}/{token}/delete', 'Dashboard\FileController@delete')->name('files.delete');
    Route::get('/finance', 'Dashboard\FinanceController@index')->name('finance');
    Route::get('/finance/recover', 'Dashboard\FinanceController@recover')->name('finance.recover');
    Route::post('/finance/recover/paypal', 'Dashboard\FinanceController@paypal')->name('finance.recover.paypal');
});

app/Http/Controllers/Dashboard/FileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class FileController extends Controller
{
    public function index(){
        $files = Auth::user()->files;
        return view('dashboard.files', compact('files'));
    }

    public function delete($slug, $token){
        if(File::where('slug', $slug)->where('token', $token)->exists()){
            $file = File::where('slug', $slug)->firstOrFail();
            Storage::disk('s3')->delete("files/".$slug);
            $file->delete();

            return redirect()->back()->with('success_file_deleted', true);
        }
    }
}

app/Http/Controllers/Dashboard/FinanceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Payment;
use App\Setting;
use App\Snap;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class FinanceController extends Controller
{
    public function index()
    {
        $setting = Setting::orderBy('id', 'desc')->firstOrFail();
        return view('dashboard.finance.index', compact('setting'));
    }

    public function recover()
    {
        $setting = Setting::orderBy('id', 'desc')->firstOrFail();
        return view('dashboard.finance.recover', compact('setting'));
    }

    public function stats(Request $request, $period='w')
    {
        if(Auth::check()){
            $benefits = Auth::user()->benefits;
            $labels = array();
            $datas = array();

            $benefits->where('created_at', '>=', Carbon::now()->subMonth(6));
            $benefits = $benefits->groupBy(function($benefit) {
                return Carbon::parse($benefit->created_at)->format('m/Y');
            });
            $start = Carbon::parse('now -6 month');
            $end = Carbon::parse('now');

            while($start < $end)
            {
                $label = $start->format('m/Y');
                $labels[] = $label;
                if($benefits->has($label)){
                    $amount = 0;
                    foreach($benefits->get($label) as $benefit){
                        $amount += $benefit->amount;
                    }
                    $datas[] = $amount;
                }else{
                    $datas[] = 0;
                }
                $start->addMonth();
            }

            unset($labels[0]);
            unset($datas[0]);

            $data = array();
            $data['labels'] = array_values($labels);
            $data['datasets'][0]['data'] = array_values($datas);

            return json_encode($data);
        }else{
            return abort(404);
        }

    }

    public function paypal(Request $request){
        $request->validate([
            'amount' => 'required|numeric|min:0.01|max:'.Auth::user()->availableMoney(),
            'email' => 'required|email'
        ]);

        $data = [
            'email' => $request->input('email')
        ];

        $user = Auth::user();

        $snap = new Snap();
        $snap->user_id = $user->id;
        $snap->ip = $request->ip();
        $snap->history = json_encode($user->payments);
        $snap->stats = json_encode(Setting::orderBy('id', 'desc')->first());
        $snap->os = json_encode($request->server);
        $snap->save();

        $payment = new Payment();
        $payment->user_id = $user->id;
        $payment->amount = $request->input('amount');
        $payment->data = json_encode($data);
        $payment->snap_id = $snap->id;
        $payment->target = Payment::TARGET_PAYPAL;
        $payment->save();

        return redirect()->back()->with('payment_success', $request->input('amount'));
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        return view('dashboard.dashboard');
    }
}

resources/views/dashboard/finance/index.blade.php
@extends('dashboard.includes.default', ['activePage' => 'finance'])

@section('title', trans('global.meta.title'))

@section('css')
<meta name="csrf-token" content="{{ csrf_token() }}" />
@endsection

@section('header')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Available Money</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ Auth::user()->availableMoney() }}</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                                            <i class="fas fa-dollar-sign"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Already Earned</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ Auth::user()->alreadyEarned() }}</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-info text-white rounded-circle shadow">
                                            <i class="fas fa-university"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Download rate</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ $setting->downloadRate }} dls</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-indigo text-white rounded-circle shadow">
                                            <i class="fas fa-download"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Video rate</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ $setting->viewRate }} views</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                                            <i class="fas fa-eye"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" style="padding-top: 20px;">
                    <div class="col-xl-12 col-lg-12">
                        <a href="{{ route('dashboard.finance.recover') }}" class="btn btn-lg btn-danger float-right"><i class="fa fa-dollar-sign"></i> Recover my money</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')
    <div class="row mt-5">
        <div class="col">
            <div class="card shadow">
                <div class="card-body">
                    <h1 class="card-title">
                        How to retrieve my money.
                    </h1>
                    <hr>
                    <p>To make money it's very simple, every time your download or videos reach the required number, your available money balance will update.</p>
                    <p>Then you just need to request a transfer of this money to the means of payment that you prefer.</p>
                    <br>
                    <h1 class="card-title">
                        Transfers list
                    </h1>
                    <hr>
                    <div class="table-responsive">
                        <table class="table align-items-center">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">Amount</th>
                                <th scope="col">Status</th>
                                <th scope="col">Target</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach(Auth::user()->payments as $payment)
                                <tr>
                                    <td>
                                        ${{ $payment->amount }} USD
                                    </td>
                                    <td>
                                        <span class="badge badge-dot mr-4">
                                          <i class="bg-warning"></i> en attente
                                        </span>
                                    </td>
                                    <td>
                                        @if($payment->target == \App\Payment::TARGET_PAYPAL)
                                            <i class="fab fa-paypal"></i> {{ \App\Payment::LIST_MEANS_PAYMENT[\App\Payment::TARGET_PAYPAL] }}@if(!empty(json_decode($payment->data)->email)) - {{ json_decode($payment->data)->email }}@endif
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript">
        function deleteFile(slug, token) {
            $('#deleteLink').attr('href', '{{ url('dashboard/files') }}/'+slug+'/'+token+'/delete')
        }
    </script>
@endsection

resources/views/dashboard/finance/recover.blade.php
@extends('dashboard.includes.default', ['activePage' => 'finance'])

@section('title', trans('global.meta.title'))

@section('css')
<meta name="csrf-token" content="{{ csrf_token() }}" />
@endsection

@section('header')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Available Money</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ Auth::user()->availableMoney() }}</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                                            <i class="fas fa-dollar-sign"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Already Earned</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ Auth::user()->alreadyEarned() }}</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-info text-white rounded-circle shadow">
                                            <i class="fas fa-university"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Download rate</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ $setting->downloadRate }} dls</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-indigo text-white rounded-circle shadow">
                                            <i class="fas fa-download"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6">
                        <div class="card card-stats mb-4 mb-xl-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">Video rate</h5>
                                        <span class="h2 font-weight-bold mb-0">${{ $setting->viewRate }} views</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                                            <i class="fas fa-eye"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')
    <div class="row mt-5">
        <div class="col">
            <div class="card shadow">
                <div class="card-body">
                    <h1 class="card-title">
                        How mutch do you want ?
                    </h1>
                    <hr>
                    @if(Session::has('payment_success'))
                        <div class="alert alert-success" role="alert">
                            <span class="alert-inner--icon"><i class="fas fa-check"></i></span>
                            <span class="alert-inner--text"><strong>Success!</strong> You have been transfered ${{ Session::get('payment_success') }} !</span>
                        </div>
                    @endif
                    <div class="alert alert-primary" role="alert">
                        <span class="alert-inner--icon"><i class="fas fa-dollar-sign"></i></span>
                        <span class="alert-inner--text"><strong>Attention!</strong> You need to have a paypal account to recover your money !</span>
                    </div>
                    <div class="nav-wrapper">
                        <ul class="nav nav-pills nav-fill flex-column flex-md-row" id="tabs-icons-text" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link mb-sm-3 mb-md-0 active" id="tabs-icons-text-1-tab" data-toggle="tab" href="#tabs-icons-text-1" role="tab" aria-controls="tabs-icons-text-1" aria-selected="true"><i class="fab fa-paypal"></i> Paypal</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link mb-sm-3 mb-md-0" id="tabs-icons-text-2-tab" data-toggle="tab" href="#tabs-icons-text-2" role="tab" aria-controls="tabs-icons-text-2" aria-selected="false"><i class="fab fa-cc-visa"></i> Visa</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="tabs-icons-text-1" role="tabpanel" aria-labelledby="tabs-icons-text-1-tab">
                                    {!! Form::open()->url(route('dashboard.finance.recover.paypal')) !!}
                                    {!! Form::text('email')->placeholder(trans('global.register.email'). ' paypal')->type('email')->attrs(['required' => 'required']) !!}
                                    {!! Form::text('amount')->placeholder('Amount')->type('number')->attrs(['required' => 'required', 'step' => '0.01', 'min' => 0, 'max' => Auth::user()->availableMoney()]) !!}
                                    <i>Maximum amount : ${{ Auth::user()->availableMoney() }}</i>
                                    <input type="submit" class="btn btn-outline-primary btn-lg float-right" value="Earn">
                                    {!! Form::close() !!}
                                </div>
                                <div class="tab-pane fade" id="tabs-icons-text-2" role="tabpanel" aria-labelledby="tabs-icons-text-2-tab">
                                    <p class="description">Coming soon...</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript">
        function deleteFile(slug, token) {
            $('#deleteLink').attr('href', '{{ url('dashboard/files') }}/'+slug+'/'+token+'/delete')
        }
    </script>
@endsection