routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/init', 'PageController@init')->name('init'); // TODO : Delete après
Route::get('/', 'PageController@index')->name('home');
Route::get('/lang/{id}', 'PageController@lang')->name('lang.choose');
Route::get('/about', 'PageController@about')->name('about');
Route::get('/faq', 'PageController@faq')->name('faq');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::post('/contact', 'PageController@postContact')->name('contact.post');
Route::get('/terms', 'PageController@terms')->name('terms');
Route::get('/privacy', 'PageController@privacy')->name('privacy');
Route::get('/copyright', 'PageController@copyright')->name('copyright');
Route::get('/report', 'PageController@report')->name('report');
Route::get('/register', 'AuthController@register')->name('register');
Route::post('/register', 'AuthController@postRegister')->name('register.post');
Route::get('/logout', 'AuthController@logout')->name('logout');
Route::post('/login', 'AuthController@postLogin')->name('login');
Route::post('/login', 'AuthController@postLogin')->name('login');
Route::get('/forgotpassword', 'AuthController@forgotPassword')->name('forgot_password');
Route::post('/forgotpassword', 'AuthController@postForgotPassword')->name('forgot_password.post');
Route::get('/resetpassword/{email}/{token}', 'AuthController@resetPassword')->name('reset_password');
Route::post('/resetpassword/{email}/{token}', 'AuthController@postResetPassword')->name('reset_password.post');
Route::post('/upload', 'UploadController@ajax')->name('upload.ajax');
Route::get('/d/{slug}/{token}', 'UploadController@delete')->name('upload.delete');
Route::get('/f/{slug}', 'PageController@file')->name('file');
Route::get('/d/{slug}', 'DownloadController@download')->name('download');
Route::get('/json/downloads/stats/{period}', 'DownloadController@stats')->name('download.stats');
Route::get('/json/money/stats', 'Dashboard\FinanceController@stats')->name('money.stats');
Route::get('/v/{slug}', 'PageController@video')->name('video');

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'noguest'], function(){
    Route::get('/', 'Dashboard\HomeController@index')->name('index');
    Route::get('/files', 'Dashboard\FileController@index')->name('files');
    Route::get('/files/{slug}/{token}/delete', 'Dashboard\FileController@delete')->name('files.delete');
    Route::get('/finance', 'Dashboard\FinanceController@index')->name('finance');
    Route::get('/finance/recover', 'Dashboard\FinanceController@recover')->name('finance.recover');
    Route::post('/finance/recover/paypal', 'Dashboard\FinanceController@paypal')->name('finance.recover.paypal');
});

app/Http/Controllers/Dashboard/FileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class FileController extends Controller
{
    public function index(){
        $files = Auth::user()->files;
        return view('dashboard.files', compact('files'));
    }

    public function delete($slug, $token){
        if(File::where('slug', $slug)->where('token', $token)->exists()){
            $file = File::where('slug', $slug)->firstOrFail();
            Storage::disk('s3')->delete("files/".$slug);
            $file->delete();

            return redirect()->back()->with('success_file_deleted', true);
        }
    }
}

app/Http/Controllers/Dashboard/FinanceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Payment;
use App\Setting;
use App\Snap;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class FinanceController extends Controller
{
    public function index()
    {
        $setting = Setting::orderBy('id', 'desc')->firstOrFail();
        return view('dashboard.finance.index', compact('setting'));
    }

    public function recover()
    {
        $setting = Setting::orderBy('id', 'desc')->firstOrFail();
        return view('dashboard.finance.recover', compact('setting'));
    }

    public function stats(Request $request, $period='w')
    {
        if(Auth::check()){
            $benefits = Auth::user()->benefits;
            $labels = array();
            $datas = array();

            $benefits->where('created_at', '>=', Carbon::now()->subMonth(6));
            $benefits = $benefits->groupBy(function($benefit) {
                return Carbon::parse($benefit->created_at)->format('m/Y');
            });
            $start = Carbon::parse('now -6 month');
            $end = Carbon::parse('now');

            while($start < $end)
            {
                $label = $start->format('m/Y');
                $labels[] = $label;
                if($benefits->has($label)){
                    $amount = 0;
                    foreach($benefits->get($label) as $benefit){
                        $amount += $benefit->amount;
                    }
                    $datas[] = $amount;
                }else{
                    $datas[] = 0;
                }
                $start->addMonth();
            }

            unset($labels[0]);
            unset($datas[0]);

            $data = array();
            $data['labels'] = array_values($labels);
            $data['datasets'][0]['data'] = array_values($datas);

            return json_encode($data);
        }else{
            return abort(404);
        }

    }

    public function paypal(Request $request){
        $request->validate([
            'amount' => 'required|numeric|min:0.01|max:'.Auth::user()->availableMoney(),
            'email' => 'required|email'
        ]);

        $data = [
            'email' => $request->input('email')
        ];

        $user = Auth::user();

        $snap = new Snap();
        $snap->user_id = $user->id;
        $snap->ip = $request->ip();
        $snap->history = json_encode($user->payments);
        $snap->stats = json_encode(Setting::orderBy('id', 'desc')->first());
        $snap->os = json_encode($request->server);
        $snap->save();

        $payment = new Payment();
        $payment->user_id = $user->id;
        $payment->amount = $request->input('amount');
        $payment->data = json_encode($data);
        $payment->snap_id = $snap->id;
        $payment->target = Payment::TARGET_PAYPAL;
        $payment->save();

        return redirect()->back()->with('payment_success', $request->input('amount'));
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        return view('dashboard.dashboard');
    }
}

resources/views/dashboard/includes/default.blade.php
<!doctype html>
<html lang="{{ App::getLocale() }}">
<head>
    <meta charset="utf-8">
    <title>uLoad - @yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{{ @url('img/favicon.png') }}" rel="icon" type="image/png">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="{{ url('vendor/nucleo/css/nucleo.css') }}" rel="stylesheet">
    <link href="{{ url('vendor/@fortawesome/fontawesome-free/css/all.min.css') }}" rel="stylesheet">
    <link type="text/css" href="{{ URL::asset('css/argon.min.css') }}" rel="stylesheet">
    <link type="text/css" href="{{ URL::asset('css/dashboard.css') }}" rel="stylesheet">
    @yield('css')
</head>

<body>
    @include('dashboard.includes.sidebar')
    <!-- Main content -->
    <div class="main-content">
        @include('dashboard.includes.menu')
        @yield('header')
        <div class="container-fluid mt--7">
            @yield('content')
            @include('dashboard.includes.footer')
        </div>
    </div>
    <script src="{{ URL::asset('vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ URL::asset('vendor/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    @yield('js')
    <script src="{{ URL::asset('js/argon.js') }}"></script>
    @yield('js2')
</body>
</html>

resources/views/dashboard/includes/footer.blade.php
<footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                &copy; 2019 <a class="font-weight-bold ml-1" target="_blank">uLoad</a>
            </div>
        </div>
        <div class="col-xl-6">
            <ul class="nav nav-footer justify-content-center justify-content-xl-end">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('about') }}">@lang('global.footer.about')</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('faq') }}">@lang('global.footer.faq')</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('contact') }}">@lang('global.footer.contact')</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('terms') }}">@lang('global.footer.terms')</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('privacy') }}">@lang('global.footer.privacy')</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('copyright') }}">@lang('global.footer.copyright')</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('report') }}">@lang('global.footer.report')</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

resources/views/dashboard/includes/menu.blade.php
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="{{ route('dashboard.index') }}">Dashboard</a>
        <!-- Form -->
        <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
            <div class="form-group mb-0">
                <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-search"></i></span>
                    </div>
                    <input class="form-control" placeholder="Search" type="text">
                </div>
            </div>
        </form>

        <ul class="navbar-nav align-items-center d-none d-md-flex">
            <li class="nav-item dropdown">
                <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                    <span class="avatar avatar-sm rounded-circle bg-gradient-indigo">
                      <i class="fas fa-user"></i>
                    </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome!</h6>
                    </div>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>My profile</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>Settings</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item">
                        <i class="ni ni-user-run"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ strtoupper(App::getLocale()) }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    @foreach(explode(',', env('LANG_ALLOWED')) as $lang)
                        <a class="dropdown-item" @if($lang != App::getLocale()) href="{{ url('lang/'.$lang) }}" @endif>{{ strtoupper($lang) }}</a>
                    @endforeach
                </div>
            </li>
        </ul>
    </div>
</nav>

resources/views/dashboard/includes/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand pt-0" href="{{ url('/') }}">
            <img src="{{ url('img/logo.png') }}" class="navbar-brand-img" alt="...">
        </a>

        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle bg-gradient-indigo">
                      <i class="fas fa-user"></i>
                    </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome!</h6>
                    </div>
                    <a href="" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>My profile</span>
                    </a>
                    <a href="" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>Settings</span>
                    </a>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item">
                        <i class="ni ni-user-run"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ strtoupper(App::getLocale()) }}
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbarDropdown">
                    @foreach(explode(',', env('LANG_ALLOWED')) as $lang)
                        <a class="dropdown-item" @if($lang != App::getLocale()) href="{{ url('lang/'.$lang) }}" @endif>{{ strtoupper($lang) }}</a>
                    @endforeach
                </div>
            </li>
        </ul>
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ url('img/logo.png') }}">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>

            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>

            <ul class="navbar-nav">
                <li class="nav-item @if( empty($activePage) or $activePage == "dashboard"){{ 'active' }}@endif">
                    <a class="nav-link " href="{{ route('dashboard.index') }}">
                        <i class="fas fa-tachometer-alt text-light"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item @if( !empty($activePage) and $activePage == "files"){{ 'active' }}@endif">
                    <a class="nav-link" href="{{ route('dashboard.files') }}">
                        <i class="ni ni-folder-17 text-light"></i> Files
                    </a>
                </li>
                <li class="nav-item @if( !empty($activePage) and $activePage == "finance"){{ 'active' }}@endif">
                    <a class="nav-link" href="{{ route('dashboard.finance') }}">
                        <i class="ni ni-money-coins text-light"></i> Finance
                    </a>
                </li>
                <li class="nav-item @if( !empty($activePage) and $activePage == "settings"){{ 'active' }}@endif">
                    <a class="nav-link" href="#">
                        <i class="ni ni-settings-gear-65 text-light"></i> Settings
                    </a>
                </li>
            </ul>
    </div>
</nav>